### ISSUE TITLE
How to get rid of this

### ISSUE THREAD

**Issue by Aldwew** [DetectiveSquirrel/SithylisQoL#3]
https://gyazo.com/a56c4b7b354b08c96b9242b8f5671d11

**Comment by DetectiveSquirrel** [comment]
i was too tired to add a settings for that as its bound to the setting for Hidden Passage.
I will add the settings for this soon.

**Comment by DetectiveSquirrel** [comment]
Is now a standalone setting, sorry for that.

**Comment by Aldwew** [comment]
Thanks
