### ISSUE TITLE
error with latest version

### ISSUE THREAD

**Issue by gixxpunk** [DetectiveSquirrel/SithylisQoL#6]
![error](https://user-images.githubusercontent.com/1607735/35099281-aca9add2-fc57-11e7-8da4-2a2b4b776f85.png)

get this error all the time

**Comment by DetectiveSquirrel** [comment]
i don't speed German(?) so I have no idea what that error means im sorry.

**Comment by DetectiveSquirrel** [comment]
Can you try menually Re-Downloading poehud from the correct branch you need to/

**Comment by Hotcooler** [comment]
It basically says "Collection cannot be enumerated because it was modified". In any case it's caused by "Update entity in parallel thread" experimental feature in hud.
